- 기본 전처리

In [1]:
import pandas as pd

data = pd.read_csv('NAVER.csv')
data1 = pd.read_csv('NAVER_FINISH.csv')
data.head()

,id,title,author,day,genre,story,score,platform
0,0,참교육,채용택 / 한가람,월,"스토리, 액션",무너진 교권을 지키기 위해 교권보호국 소속 나화진의 참교육이 시작된다! 부활남 채용...,9.776,네이버 웹툰
1,1,신의 탑,SIU,월,"스토리, 판타지",자신의 모든 것이었던 소녀를 쫓아 탑에 들어온 소년 그리고 그런 소년을 시험하는 탑,9.499,네이버 웹툰
2,2,뷰티풀 군바리,설이 / 윤성원,월,"스토리, 드라마",여자도 군대에 간다면? 본격 여자도 군대 가는 만화!,9.660,네이버 웹툰
3,3,윈드브레이커,조용석,월,"스토리, 스포츠",혼자서 자전거를 즐겨타던 모범생 조자현. 원치 않게 자전거 크루의 일에 자꾸 휘말리...,8.795,네이버 웹툰
4,4,팔이피플,매미 / 희세,월,"스토리, 드라마","마스크걸 , 위대한 방옥숙 매미 희세 작가의 신작! 에서 육아용품 파는 평범한 유부...",9.880,네이버 웹툰

In [2]:
import sys
sys.version

'3.8.11 (default, Aug  6 2021, 09:57:55) [MSC v.1916 64 bit (AMD64)]'

In [3]:
data1.head(3)

,id,title,author,genre,story,score,platform
0,0,국왕과 성기사의 약탈혼,이린비 / 박지은,"스토리, 로맨스","그래, 왕이 되었지. 가지고 싶은 건 다 빼앗아 가지려고. 왕위를 찬탈하고 주변국을...",9.78,네이버 웹툰
1,1,성경의 역사,최경민 / 영모,"스토리, 드라마","모두에게 사랑 받기에 모두가 증오하는 그녀, 성경 .원치않는 애정과 증오속에 성경의...",7.43,네이버 웹툰
2,2,이츠마인,럭스,"스토리, 스릴러","어떻게 해야 널 지킬 수 있을까, 다정아? 10년 뒤 다정이가 죽는다는 메시지를 본...",9.97,네이버 웹툰

In [4]:
df = data.append(data1, ignore_index=True)
df.fillna('완결',inplace=True)
df.isnull().sum()

id          0
title       0
author      0
day         0
genre       0
story       0
score       0
platform    0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        1470 non-null   int64
 1   title     1470 non-null   object
 2   author    1470 non-null   object
 3   day       1470 non-null   object
 4   genre     1470 non-null   object
 5   story     1470 non-null   object
 6   score     1470 non-null   float64
 7   platform  1470 non-null   object
dtypes: float64(1), int64(1), object(6)
memory usage: 92.0+ KB

In [6]:
webtoon = df.copy()
webtoon

,id,title,author,day,genre,story,score,platform
0,0,참교육,채용택 / 한가람,월,"스토리, 액션",무너진 교권을 지키기 위해 교권보호국 소속 나화진의 참교육이 시작된다! 부활남 채용...,9.776,네이버 웹툰
1,1,신의 탑,SIU,월,"스토리, 판타지",자신의 모든 것이었던 소녀를 쫓아 탑에 들어온 소년 그리고 그런 소년을 시험하는 탑,9.499,네이버 웹툰
2,2,뷰티풀 군바리,설이 / 윤성원,월,"스토리, 드라마",여자도 군대에 간다면? 본격 여자도 군대 가는 만화!,9.660,네이버 웹툰
3,3,윈드브레이커,조용석,월,"스토리, 스포츠",혼자서 자전거를 즐겨타던 모범생 조자현. 원치 않게 자전거 크루의 일에 자꾸 휘말리...,8.795,네이버 웹툰
4,4,팔이피플,매미 / 희세,월,"스토리, 드라마","마스크걸 , 위대한 방옥숙 매미 희세 작가의 신작! 에서 육아용품 파는 평범한 유부...",9.880,네이버 웹툰
...,...,...,...,...,...,...,...,...
1465,1020,AA,"선정, 지숙",완결,"스토리, 로맨스",대머리 사절을 외치는 여인과 대머리 일것 같은 그녀의 이상형이 벌이는 로맨틱 코미디...,9.680,네이버 웹툰
1466,1021,사랑in,전세훈,완결,"옴니버스, 로맨스",전세훈의 감성터치 사랑 우리들의 이야기가 수채화 물감처럼 잔잔한 감동으로. 잃어버린...,9.510,네이버 웹툰
1467,1022,까뱅,X-TEAM,완결,"에피소드, 개그",치킨시티의 새로운 영웅 까뱅 오늘도 그의 활약은 계속된다!,8.830,네이버 웹툰
1468,1023,와탕카,우주인,완결,"에피소드, 개그","와탕카 만세 , 지화자 좋은 패가 들어오면 외치는 단어 와탕카! 우주인 작가님의 불...",9.630,네이버 웹툰
1469,1024,타투,노지현,완결,"옴니버스, 드라마","밝고 쾌활한 여고생 현진과 새로 오픈한 타투 가게의 진우, 유기를 중심으로 벌어지는...",9.200,네이버 웹툰

-  작가 중 선정, 지숙 은 /로 나눠져있지않고 ,로 나누어져 있어서 특수문자 제거 후 분리
-  장르 카테고리(스토리, 옵니버스 등) 삭제

In [7]:
webtoon['author'] = webtoon['author'].str.replace(pat=r'[^\w]', repl=r' ', regex=True)
webtoon['writer'] = webtoon['author'].apply(lambda x: x.split(' ')[0])
webtoon['illustrator'] = webtoon['author'].apply(lambda x:x.split(' ')[-1])

webtoon['genre'] = webtoon['genre'].apply(lambda x: x.split(',')[-1])
webtoon.drop(columns='author', inplace=True)

In [8]:
webtoon

,id,title,day,genre,story,score,platform,writer,illustrator
0,0,참교육,월,액션,무너진 교권을 지키기 위해 교권보호국 소속 나화진의 참교육이 시작된다! 부활남 채용...,9.776,네이버 웹툰,채용택,한가람
1,1,신의 탑,월,판타지,자신의 모든 것이었던 소녀를 쫓아 탑에 들어온 소년 그리고 그런 소년을 시험하는 탑,9.499,네이버 웹툰,SIU,SIU
2,2,뷰티풀 군바리,월,드라마,여자도 군대에 간다면? 본격 여자도 군대 가는 만화!,9.660,네이버 웹툰,설이,윤성원
3,3,윈드브레이커,월,스포츠,혼자서 자전거를 즐겨타던 모범생 조자현. 원치 않게 자전거 크루의 일에 자꾸 휘말리...,8.795,네이버 웹툰,조용석,조용석
4,4,팔이피플,월,드라마,"마스크걸 , 위대한 방옥숙 매미 희세 작가의 신작! 에서 육아용품 파는 평범한 유부...",9.880,네이버 웹툰,매미,희세
...,...,...,...,...,...,...,...,...,...
1465,1020,AA,완결,로맨스,대머리 사절을 외치는 여인과 대머리 일것 같은 그녀의 이상형이 벌이는 로맨틱 코미디...,9.680,네이버 웹툰,선정,지숙
1466,1021,사랑in,완결,로맨스,전세훈의 감성터치 사랑 우리들의 이야기가 수채화 물감처럼 잔잔한 감동으로. 잃어버린...,9.510,네이버 웹툰,전세훈,전세훈
1467,1022,까뱅,완결,개그,치킨시티의 새로운 영웅 까뱅 오늘도 그의 활약은 계속된다!,8.830,네이버 웹툰,X,TEAM
1468,1023,와탕카,완결,개그,"와탕카 만세 , 지화자 좋은 패가 들어오면 외치는 단어 와탕카! 우주인 작가님의 불...",9.630,네이버 웹툰,우주인,우주인
1469,1024,타투,완결,드라마,"밝고 쾌활한 여고생 현진과 새로 오픈한 타투 가게의 진우, 유기를 중심으로 벌어지는...",9.200,네이버 웹툰,노지현,노지현

In [9]:
wt = pd.DataFrame(webtoon, columns=['id','title','writer','illustrator','day','genre','story','score','platform'])
wt.head()

,id,title,writer,illustrator,day,genre,story,score,platform
0,0,참교육,채용택,한가람,월,액션,무너진 교권을 지키기 위해 교권보호국 소속 나화진의 참교육이 시작된다! 부활남 채용...,9.776,네이버 웹툰
1,1,신의 탑,SIU,SIU,월,판타지,자신의 모든 것이었던 소녀를 쫓아 탑에 들어온 소년 그리고 그런 소년을 시험하는 탑,9.499,네이버 웹툰
2,2,뷰티풀 군바리,설이,윤성원,월,드라마,여자도 군대에 간다면? 본격 여자도 군대 가는 만화!,9.660,네이버 웹툰
3,3,윈드브레이커,조용석,조용석,월,스포츠,혼자서 자전거를 즐겨타던 모범생 조자현. 원치 않게 자전거 크루의 일에 자꾸 휘말리...,8.795,네이버 웹툰
4,4,팔이피플,매미,희세,월,드라마,"마스크걸 , 위대한 방옥숙 매미 희세 작가의 신작! 에서 육아용품 파는 평범한 유부...",9.880,네이버 웹툰

- 특수문자 및 숫자 삭제

In [10]:
import re

def kor(text):
    return re.sub('[^ㄱ-ㅣ가-힣]', ' ', text)

temp_txt = wt['story'][41]
print(temp_txt)
print(kor(temp_txt))

짝사랑은 이제 그만! 고잉고등학교에서 가장 핫한 소문, 헌옷수거함에 돈을 넣고 좋아하는 사람의 이름을 외치면 상대방의 마음을 알려준다는데..! 연애 대신 성적과 돈에만 관심 있는 송아람은 그런 소문에 휘둘리지 않는다. 그런 아람의 일상에 학교 인기남 정진우가 불쑥 들어온다. 어디로 튈지 모르는 이 자식을 어떻게 해야 좋을까?
짝사랑은 이제 그만  고잉고등학교에서 가장 핫한 소문  헌옷수거함에 돈을 넣고 좋아하는 사람의 이름을 외치면 상대방의 마음을 알려준다는데    연애 대신 성적과 돈에만 관심 있는 송아람은 그런 소문에 휘둘리지 않는다  그런 아람의 일상에 학교 인기남 정진우가 불쑥 들어온다  어디로 튈지 모르는 이 자식을 어떻게 해야 좋을까

In [11]:
df = wt.copy()
df['story'] = df['story'].apply(lambda x:kor(x))
df.head(3)

,id,title,writer,illustrator,day,genre,story,score,platform
0,0,참교육,채용택,한가람,월,액션,무너진 교권을 지키기 위해 교권보호국 소속 나화진의 참교육이 시작된다 부활남 채용...,9.776,네이버 웹툰
1,1,신의 탑,SIU,SIU,월,판타지,자신의 모든 것이었던 소녀를 쫓아 탑에 들어온 소년 그리고 그런 소년을 시험하는 탑,9.499,네이버 웹툰
2,2,뷰티풀 군바리,설이,윤성원,월,드라마,여자도 군대에 간다면 본격 여자도 군대 가는 만화,9.660,네이버 웹툰

- 불용어(stop word) 제거

In [12]:
with open('stopwords_korean.txt','r', encoding='utf-8') as f :
    stopwords = f.readline()
stopwords = stopwords.split()
print(stopwords[:10])

['아', '휴', '아이구', '아이쿠', '아이고', '어', '나', '우리', '저희', '따라']

- 토큰화

In [14]:
from konlpy.tag import Okt,Hannanum,Kkma,Komoran,Mecab
okt = Okt() #okt : open korean text
hannanum = Hannanum() #Hannanum : Kaist
kkma = Kkma() #Kkma : 서울대
komoran = Komoran() # komoran : Shinware
mecab = Mecab(dicpath="C:\\mecab\\mecab-ko-dic") #Mecab

# okt
def okt_tokenizer(text):
    tokens_ko = okt.morphs(text)
    filtered_words = []
    # 각 문장에 대해 스톱 워드 제거
    for word in token_ko :
        if word not in stopwords:
            filtered_words.append(word)
            
    return filtered_words

# Hannanum

def hannanum_tokenizer(text):
    tokens_ko = hannanum.morphs(text)
    filtered_words = []
    # 각 문장에 대해 스톱 워드 제거
    for word in token_ko :
        if word not in stopwords:
            filtered_words.append(word)
            
    return filtered_words

# Komoran
def komoran_tokenizer(text):
    # 입력 인자로 들어온 텍스트를 형태소 단어로 토큰화해 리스트 형태로 반환
    tokens_ko = komoran.morphs(text)
    filtered_words = []
    # 각 문장별 단어에 대해 스톱 워드 제거
    for word in tokens_ko:
        if word not in stopwords:
            filtered_words.append(word)
    
    return filtered_words

#Macab
def mecab_tokenizer(text):
    # 입력 인자로 들어온 텍스트를 형태소 단어로 토큰화해 리스트 형태로 반환
    tokens_ko = mecab.morphs(text)
    filtered_words = []
    # 각 문장별 단어에 대해 스톱 워드 제거
    for word in tokens_ko:
        if word not in stopwords:
            filtered_words.append(word)
    
    return filtered_words